# CloudSync - Web Admin
# React App
# .travis.yml

# Basado en:
# https://dev.to/michalhonc/set-up-continuous-deploy-for-free-with-react-github-travis-and-heroku-381b

os: [ "linux" ]
dist: "xenial"
language: node_js
node_js:
  - 17
# before_install:
#
install:
# install requirements
- npm --prefix cloudsync-web-admin install
script:
# run tests
- npm --prefix cloudsync-web-admin test -- --coverage
# build optimized production version
- npm --prefix cloudsync-web-admin run build
after_success:
  # submit results to coveralls, on success
  - coveralls
branches:
  # include ONLY these branches
  only:
    - qa
    - master
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  strategy: api
  app:
    qa: $HEROKU_APP_NAME_QA
    master: $HEROKU_APP_NAME
