# CloudSync - Web Admin
# React App
# .travis.yml

# Basado en:
# https://stackoverflow.com/questions/60909911/how-do-i-deploy-a-static-react-app-to-heroku
# https://dev.to/michalhonc/set-up-continuous-deploy-for-free-with-react-github-travis-and-heroku-381b
# https://dev.to/nedsoft/ci-cd-with-travisci-and-coveralls-in-node-express-api-2i55

os: [ "linux" ]
dist: "xenial"
language: node_js
node_js:
  - 16
services:
  - docker
before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
  #- cd cloudsync-web-admin
# install:
  # install requirements
  # - npm install
script:
  # run tests
  #- npm run test -- --coverage
  - echo "Tests disabled."
#after_success:
  # submit results to coveralls, on success
  #- cat ./coverage/lcov.info | coveralls
branches:
  # include ONLY these branches
  only:
    - qa
    - master
deploy:
  - provider: script
    script:
      # build docker images, push to dockerhub & heroku
      docker build -t juanmg0511/7599-trabajoprofesional-cloudsync-webadmin:qa .;
      docker tag juanmg0511/7599-trabajoprofesional-cloudsync-webadmin:qa registry.heroku.com/$HEROKU_APP_NAME_QA/web;
      docker push juanmg0511/7599-trabajoprofesional-cloudsync-webadmin:qa;
      docker push registry.heroku.com/$HEROKU_APP_NAME_QA/web;
      heroku container:release web --app $HEROKU_APP_NAME_QA
    on:
      branch: qa

  - provider: script
    script:
      # build docker images, push to dockerhub & heroku
      docker build -t juanmg0511/7599-trabajoprofesional-cloudsync-webadmin:production .;
      docker tag juanmg0511/7599-trabajoprofesional-cloudsync-webadmin:production registry.heroku.com/$HEROKU_APP_NAME/web;
      docker push juanmg0511/7599-trabajoprofesional-cloudsync-webadmin:production;
      docker push registry.heroku.com/$HEROKU_APP_NAME/web;
      heroku container:release web --app $HEROKU_APP_NAME
    on:
      branch: master
