# CloudSync - Web Admin
# React App
# .travis.yml

# Basado en:
# https://dev.to/michalhonc/set-up-continuous-deploy-for-free-with-react-github-travis-and-heroku-381b
# https://dev.to/nedsoft/ci-cd-with-travisci-and-coveralls-in-node-express-api-2i55

os: [ "linux" ]
dist: "xenial"
language: node_js
node_js:
  - 17
before_install:
- cd cloudsync-web-admin
install:
# install requirements
- npm install
script:
# run tests
- nyc npm test && nyc report --reporter=text-lcov
# build optimized production version
- npm run build
after_success:
  # submit results to coveralls, on success
  - coveralls
branches:
  # include ONLY these branches
  only:
    - qa
    - master
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  strategy: api
  api_key: $HEROKU_API_KEY
  app:
    qa: $HEROKU_APP_NAME_QA
    master: $HEROKU_APP_NAME
