# CloudSync - Web Admin
# React App
# .travis.yml

# Basado en:
# https://dev.to/michalhonc/set-up-continuous-deploy-for-free-with-react-github-travis-and-heroku-381b

os: [ "linux" ]
dist: "xenial"
languaje: node_js
node_js:
  - 18
before_install:
- npm --prefix cloudsync-web-admin update
install:
# install requirements
- npm --prefix cloudsync-web-admin install
- npm --prefix cloudsync-web-admin build
script:
# run tests
- npm --prefix cloudsync-web-admin test
after_success:
  # submit results to coveralls, on success
  - coveralls
branches:
  # include ONLY these branches
  only:
    - qa
    - master
deploy:
  provider: heroku
  app:
    qa: $HEROKU_APP_NAME_QA
    master: $HEROKU_APP_NAME
